= Emerald API for Java
:lib-version: 0.11.0

image:https://github.com/emeraldpay/emerald-java-client/workflows/Tests/badge.svg["Unit Tests"]
image:https://img.shields.io/github/license/emeraldpay/emerald-java-client.svg?maxAge=2592000["License",link="https://github.com/emeraldpay/emerald-java-client/blob/master/LICENSE"]
image:https://badges.gitter.im/emeraldpay/community.svg[link="https://gitter.im/emeraldpay/community?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge"]
image:https://codecov.io/gh/emeraldpay/emerald-java-client/branch/master/graph/badge.svg["Coverage",link="https://codecov.io/gh/emeraldpay/emerald-java-client"]

Java stubs for public Emerald gRPC APIs.

== Requirements

----
Java:        java 11.0.17 2022-10-18 LTS (openjdk@11)
Gradle:      7.6
Kotlin:      1.7.10
Groovy:      3.0.13
Ant:         Apache Ant(TM) version 1.10.11 compiled on July 10 2021
JVM:         17.0.5 (Homebrew 17.0.5+0)
OS:          Mac OS X 13.1 aarch64 (M1)
----

== Usage

=== Dependency

If you want to use the Emerald Java Client from another project, include those lines into your `build.gradle` file :
[source,groovy,subs="attributes"]
----
repositories {
    maven { url  "https://maven.emrld.io" }
}

dependencies {
    implementation 'io.emeraldpay:emerald-api:{lib-version}'
}
----

== Development

If you want to build your own version of the Emerald Java Client, you first need to update the Emerald gRPC submodule whose depend on the Emerald Java Client.

Original Protobuf definitions are located at: https://github.com/emeraldpay/emerald-grpc

.Update Emerald gRPC (Protobuf) submodule:
[source,bash]
----
git submodule update --init
----

Then, you can build your Emerald Java Client with gradle:

.Build your client:
[source,bash]
----
gradle build
----

== License

Copyright 2021 EmeraldPay, Inc

Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and limitations under the License.